---
title: "include"
author: "Paul Sprouse"
date: "9/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library ####
library(shiny)
# library(dplyr)
# library(tidyverse)
# library(ggplot2)
# library(DBI)
# library(RSQLite)
# library(DT)
# library(shinythemes)
# library(latticeExtra)
# library(plotly)
# library(viridis)
# library(tm)
# library(wordcloud)
# library(wordcloud2)
# library(RColorBrewer)
# library(markdown)
# library(hexbin)
# library(scatterplot3d)
# library(rgl)
# library(skimr)
```
## Load Data
Data from 4 tables was combined using SQL, here i connect to the database
I also load a steriod list

```{r}
# data connection to db and Load steroid list####
# connector <- function(con, db) {
#     con <- dbConnect(SQLite(), db)
#     return (con)
# }
# dbcon <- connector(con, "baseball_stats.db")
# as.data.frame(dbListTables(dbcon))
# stats <- dbReadTable(dbcon, 'bat_p')
# teams <- dbReadTable(dbcon, 'Teams')
# # The steroid list from - https://bleacherreport.com/articles/232808-steroidology-l-hoops-projects-all-104-players-on-the-2003-steroid-list
# the_list <- read_csv('steroid_list.csv')
# dbDisconnect(dbcon) # disconnect
# # ** setting up data ** ####
# # HR breaks and yrs breaks
# breaks_HR = c(0, 30, 40, 50, 80)
# breaks_yrs = c(1914, 1945, 1994, 2006, 2020)
# # two data frames stats and the list - need to merge into one!
# the_list <- the_list %>% rename(nameLast = last, nameFirst = first)
# stats <- merge(x = stats,
#                y = the_list,
#                c("nameLast", "nameFirst"),
#                all.x = TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE}


# data connection to db and Load steroid list####

# 
# # Just selecting the columns that I need
# stats <-
#     stats %>% select(
#         playerID,
#         yearID,
#         nameFirst,
#         nameLast,
#         age,
#         theList,
#         weight,
#         birthYear,
#         teamID,
#         num_years,
#         G,
#         AB,
#         H,
#         HR
#     )
# # HR by at Bats - must have at least one at bat!
# # b_avg is the batting average (hits/AB)
# # HR_per_500 is HR/AB*500 - compare all batters as if they had same at bats per season
# # adding bins for time period and HR per season
# stats <-
#     stats %>% filter(AB > 0) %>% mutate(per_at_bat = HR / AB, b_avg = (H / AB)) %>%
#     mutate(theList = ifelse(is.na(theList), FALSE, TRUE)) %>%
#     mutate(HR_per_500 = per_at_bat * 500) %>%
#     mutate(HR_after_31 = ifelse(age > 31, HR, 0)) %>%
#     mutate(HR_bin = cut(
#         HR,
#         breaks = breaks_HR,
#         include.lowest = TRUE,
#         right = FALSE,
#         labels = c("under 30", "30 to 40", "40 to 50", "over 50")
#     )) %>%
#     mutate(y_bin = cut(
#         yearID,
#         breaks = breaks_yrs,
#         include.lowest = TRUE,
#         right = FALSE,
#         labels = c(
#             "1914_1945",
#             "The_50yrs_before_roids",
#             "during_steroids",
#             "after_steroids"
#         )
#     ))
# # sum_top is the top 500 HR hitting seasons --> all have over 35 HR
# sum_top <- stats %>% filter(HR > 35, AB > 200) %>%
#     arrange(desc(HR_per_500)) %>%
#     top_n(500, HR_per_500) %>%
#     group_by(., playerID, theList) %>%
#     summarise(
#         n = n(),
#         max(HR),
#         max(HR_per_500),
#         min(HR_per_500),
#         mean(HR_per_500),
#         mean_age_per_top = mean(age),
#         max_age = max(age)
#     )
# stats_grouped <-
#     stats %>% group_by(playerID, theList) %>% summarise(
#         n = n(),
#         car_mean_HR = mean(HR),
#         car_mean_AB = mean(AB),
#         car_mean_HRp500 = mean(HR_per_500),
#         tot_HR = sum(HR),
#         car_avg = mean(b_avg) * 100,
#         max_age = max(age),
#         HR_after_31 = sum(HR_after_31),
#         percent_after_31 = sum(HR_after_31 / sum(HR) * 100),
#         last_year = max(yearID)
#     ) %>%
#     mutate_if(is.numeric, round, digits = 1) %>%
#     mutate(percent_after_31 = percent_after_31 / 100, car_avg = car_avg / 100)
# sum_top_c <-
#     merge(x = sum_top,
#           y = stats_grouped,
#           "playerID",
#           all.x = TRUE)
# names(sum_top_c)[3] <- "n_yrs_top"
# names(sum_top_c)[4] <- "Max_HR_T"
# names(sum_top_c)[5] <- "Max_HR(500)-T"
# names(sum_top_c)[6] <- "Min_HR(500)-T"
# names(sum_top_c)[7] <- "Mean_HR(500)-T"
# names(sum_top_c)[8] <- "Mean_Age-T"
# names(sum_top_c)[9] <- "Max_age_in_top"
# names(sum_top_c)[11] <- "n_yrs"
# names(sum_top_c)[12] <- "Mean_HR"
# names(sum_top_c)[13] <- "Mean_AB"
# names(sum_top_c)[14] <- "Mean_HR(500)"
# sum_top_c <-
#     sum_top_c %>% mutate("Mean_Age-T" = round(`Mean_Age-T`, digits = 1))
# 
# max_hr_year_stat <-
#     (stats %>% filter(HR > 20) %>% group_by(playerID) %>% top_n(1, HR) %>% arrange(desc(HR)))
# #max_hr_year_stat %>% group_by(y_bin) %>% summarize(mean(age), mean(HR), n =n())
# by_bins <-
#     stats %>% group_by(y_bin, HR_bin) %>%
#     summarize(mean(age), mean(HR), n = n()) %>% arrange(desc(HR_bin))
# # team stats ####
# teams_adj <-
#     teams %>% group_by(yearID) %>% summarise(
#         avg_G = mean(G),
#         n = n(),
#         tot_HR = sum(HR),
#         avg_HR = mean(HR),
#         avg_R = mean(R),
#         b_avg = sum(H) / sum(AB)
#     ) %>%
#     mutate(adj_avg_HR = (avg_HR / avg_G * 162),
#            adj_avg_R = (avg_R / avg_G * 162))

# end of data setup
```
UI code

```{r}

# Run the application
shinyApp(ui = ui, server = server)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
